services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: ".env"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data
    ports:
      - "${DB_PORT}:5432"

  app:
    build:  .
    env_file: ".env"
    depends_on:
      - db

volumes:
  db_data:
